### ISSUE TITLE
nuget package さがす[1 h]

### ISSUE THREAD

**Issue by papinianus** [papinianus/ColumnCounter#2]
- [ ] #2
   - excel
   - commandline args

**Comment by papinianus** [comment]
System.CommandLine がいいかも
https://learn.microsoft.com/ja-jp/dotnet/standard/commandline/
https://blog.yucchiy.com/2021/03/intro-system-commandline/

CommandLineParser は更新が古そう
https://qiita.com/kawaidainf/items/0aeace9a49b9770e2545

https://excel-memo.com/vcs-library/
EPPlus か ClosedXML か

**Comment by kota2038** [comment]
System.CommandLineとClosedXMLを入れました。
